# Generated by Django 2.1.3 on 2018-12-01 04:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0003_auto_20181129_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
